name: Continuous Integration - ZSTD Module
on:
  # Avoid triggering on pushes to /all/ open PR branches.
  push:
    branches:
      - main
    paths:
      - 'xls/modules/zstd/**'
  pull_request:
    branches:
      - main
    paths:
      - 'xls/modules/zstd/**'
  # This lets us trigger manually from the UI.
  workflow_dispatch:

jobs:
  build:
    name: Bazel Build (opt)
    runs-on:
      labels: ubuntu-22.04-64core
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v2

      - name: Restore Nightly Bazel Cache
        uses: actions/cache/restore@v4
        with:
          path: "~/.cache/bazel"
          key: bazel-cache-nightly-${{ runner.os }}-${{ github.sha }}
          restore-keys: bazel-cache-nightly-${{ runner.os }}-

      - name: Install dependencies via apt
        run: sudo apt-get install python3-distutils python3-dev python-is-python3 libtinfo5  build-essential liblapack-dev libblas-dev gfortran

      - name: Bazel Build Tools (opt)
        run: |
          bazel build -c opt --test_output=errors -- //xls/dslx:interpreter_main //xls/dslx/ir_convert:ir_converter_main //xls/tools:opt_main //xls/tools:codegen_main

      - name: Bazel Test All (opt)
        run: |
          bazel test -c opt --test_output=errors -- //xls/modules/zstd/...
